name: validation
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: actions/checkout@v2
      - run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: actions/checkout@v2
      - run: make test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: actions/checkout@v2
      - run: make build
